/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.hvl.dat250.thomas.exp1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import no.hvl.dat250.thomas.exp1.Converter;

class AppTest {
    @Test void ConversionTest1() {
        final double IN_TO_METER = 0.0254;
        final double FT_TO_METER = 0.3048;
        final double MI_TO_METER = 1609.344;

        double value = 10;
        String inStr = "m";
        String outStr = "in";

        double answer = value / IN_TO_METER;

        assertEquals(answer, Converter.convert(value, inStr, outStr));
    }

    @Test void ConversionTest2() {
        final double IN_TO_METER = 0.0254;
        final double FT_TO_METER = 0.3048;
        final double MI_TO_METER = 1609.344;
        double value = 50;
        String inStr = "ft";
        String outStr = "m";

        double answer = value * FT_TO_METER;

        assertEquals(answer, Converter.convert(value, inStr, outStr));
    }
}
